server:
  port: 9001
  shutdown: graceful

debug: false
logging:
  config: classpath:log4j2-source.xml

spring:
  application:
    name: DATACHECKER-EXTRACT-${spring.extract.endpoint}
  lifecycle:
    timeout-per-shutdown-phase: 5

  extract:
    schema: test
    databaseType: MS  # MS mysql
    endpoint: SOURCE
    query-dop: 8 # jdbc Parallel Query  config
    debezium-enable: false # Whether to enable incremental debezium configuration (not enabled by default)
    debezium-topic:
    debezium-groupId: debezium-extract-group
    debezium-topic-partitions: 1
    debezium-tables:
    debezium-serializer: AvroSerializer # StringSerializer or AvroSerializer
    debezium-avro-registry: http://localhost:8081 # avro schema registry
    debezium-time-period: 1 # Debezium incremental migration verification time period: 24 * 60 unit: Min
    # debezium-num-period: Debezium incremental migration verification is the threshold value of the number
    # of incremental change records. The default value is 1000. The threshold value should be greater than 100
    debezium-num-period: 1000
    sync-extract: false

  datasource:
    druid:
      dataSourceOne:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxxxxx:xxx/xxx?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: xxxxx
        password: xxxxxx
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
